name: ReleaseBuild

on: [push]

jobs:
  build:
  
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nuget
      uses: warrenbuckley/Setup-Nuget@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: nuget restore $Env:GITHUB_WORKSPACE\TexturePackerDeserializer\TexturePackerDeserializer.csproj

    - name: MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: MSBuild.exe $Env:GITHUB_WORKSPACE\TexturePackerDeserializer\TexturePackerDeserializer.csproj -p:Configuration=Release
      timeout-minutes: 5

    - name: Upload
      uses: actions/upload-artifact@v1.0.0
      with:
        name: artifacts
        path: TexturePackerDeserializer\bin\Release\TexturePackerDeserializer.exe
